image: 'rust:latest'

stages:
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

test:
  stage: build
  script:
    - rustc --version
    - cargo --version
    - cargo build --verbose
