sudo: false
language: rust
rust:
    - stable
before_script:
    - pip install 'travis-cargo>=0.1.0,<0.2.0' --user
    - pip install 'CppHeaderParser>=2.7.2,<3.0.0' --user
    - export PATH="$HOME/.local/bin:$PATH"
script:
    - travis-cargo build
